/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wr_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[44] = {40, 1, 0, 40, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* External functions */
int tcn(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* tcn:(i0[5x6])->(o0[5x6]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (tcn(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* wr_dyn_disc_phi_fun:(i0[40],i1[2],i2[])->(o0[40]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+3, *cr, *cs;
  casadi_real *w0=w+0, *w1=w+15, *w2=w+30, *w3=w+45, *w4=w+60, w5, *w6=w+91, *w7=w+101, *w8=w+111, *w9=w+151, *w10=w+191, *w11=w+196, *w12=w+216, *w13=w+236, w14, w15, *w16=w+246, *w17=w+248, *w18=w+278, *w19=w+308, *w20=w+328, *w21=w+358;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 15, w0);
  /* #1: @0 = reshape(@0) */
  /* #2: @1 = @0' */
  for (i=0, rr=w1, cs=w0; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #3: @2 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+15 : 0, 15, w2);
  /* #4: @2 = reshape(@2) */
  /* #5: @3 = @2' */
  for (i=0, rr=w3, cs=w2; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #6: @4 = horzcat(@1, @3) */
  rr=w4;
  for (i=0, cs=w1; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<15; ++i) *rr++ = *cs++;
  /* #7: @5 = 0.00166667 */
  w5 = 1.6666666666666668e-03;
  /* #8: @1 = @0' */
  for (i=0, rr=w1, cs=w0; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #9: @0 = @2' */
  for (i=0, rr=w0, cs=w2; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #10: @6 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+30 : 0, 10, w6);
  /* #11: @6 = reshape(@6) */
  /* #12: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<5; ++i) for (j=0; j<2; ++j) rr[i+j*5] = *cs++;
  /* #13: @8 = horzcat(@1, @0, @7) */
  rr=w8;
  for (i=0, cs=w1; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w0; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<10; ++i) *rr++ = *cs++;
  /* #14: @9 = @8' */
  for (i=0, rr=w9, cs=w8; i<8; ++i) for (j=0; j<5; ++j) rr[i+j*8] = *cs++;
  /* #15: @1 = @9[:40:8;3:6] */
  for (rr=w1, ss=w9+0; ss!=w9+40; ss+=8) for (tt=ss+3; tt!=ss+6; tt+=1) *rr++ = *tt;
  /* #16: @0 = @1' */
  for (i=0, rr=w0, cs=w1; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #17: @10 = @9[2:42:8] */
  for (rr=w10, ss=w9+2; ss!=w9+42; ss+=8) *rr++ = *ss;
  /* #18: @10 = @10' */
  /* #19: @11 = horzcat(@0, @10) */
  rr=w11;
  for (i=0, cs=w0; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<5; ++i) *rr++ = *cs++;
  /* #20: @12 = @11' */
  for (i=0, rr=w12, cs=w11; i<4; ++i) for (j=0; j<5; ++j) rr[i+j*4] = *cs++;
  /* #21: @0 = @12[:20:4;:3] */
  for (rr=w0, ss=w12+0; ss!=w12+20; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #22: @1 = @0' */
  for (i=0, rr=w1, cs=w0; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #23: @13 = @9[:32:8;6:8] */
  for (rr=w13, ss=w9+0; ss!=w9+32; ss+=8) for (tt=ss+6; tt!=ss+8; tt+=1) *rr++ = *tt;
  /* #24: @14 = input[1][0] */
  w14 = arg[1] ? arg[1][0] : 0;
  /* #25: @15 = input[1][1] */
  w15 = arg[1] ? arg[1][1] : 0;
  /* #26: @16 = vertcat(@14, @15) */
  rr=w16;
  *rr++ = w14;
  *rr++ = w15;
  /* #27: @7 = horzcat(@13, @16) */
  rr=w7;
  for (i=0, cs=w13; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<2; ++i) *rr++ = *cs++;
  /* #28: @6 = @7' */
  for (i=0, rr=w6, cs=w7; i<5; ++i) for (j=0; j<2; ++j) rr[i+j*5] = *cs++;
  /* #29: @10 = @12[3:23:4] */
  for (rr=w10, ss=w12+3; ss!=w12+23; ss+=4) *rr++ = *ss;
  /* #30: @10 = @10' */
  /* #31: @17 = horzcat(@1, @6, @10) */
  rr=w17;
  for (i=0, cs=w1; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w6; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<5; ++i) *rr++ = *cs++;
  /* #32: @18 = tcn(@17) */
  arg1[0]=w17;
  res1[0]=w18;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #33: @14 = 0.005 */
  w14 = 5.0000000000000001e-03;
  /* #34: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<6; ++i) for (j=0; j<5; ++j) rr[i+j*6] = *cs++;
  /* #35: @1 = @17[:30:6;3:6] */
  for (rr=w1, ss=w17+0; ss!=w17+30; ss+=6) for (tt=ss+3; tt!=ss+6; tt+=1) *rr++ = *tt;
  /* #36: @0 = @1' */
  for (i=0, rr=w0, cs=w1; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #37: @10 = @17[2:32:6] */
  for (rr=w10, ss=w17+2; ss!=w17+32; ss+=6) *rr++ = *ss;
  /* #38: @10 = @10' */
  /* #39: @11 = horzcat(@0, @10) */
  rr=w11;
  for (i=0, cs=w0; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<5; ++i) *rr++ = *cs++;
  /* #40: @19 = @11' */
  for (i=0, rr=w19, cs=w11; i<4; ++i) for (j=0; j<5; ++j) rr[i+j*4] = *cs++;
  /* #41: @19 = (@14*@19) */
  for (i=0, rr=w19, cs=w19; i<20; ++i) (*rr++)  = (w14*(*cs++));
  /* #42: @19 = (@12+@19) */
  for (i=0, rr=w19, cr=w12, cs=w19; i<20; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #43: @0 = @19[:20:4;:3] */
  for (rr=w0, ss=w19+0; ss!=w19+20; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #44: @1 = @0' */
  for (i=0, rr=w1, cs=w0; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #45: @10 = @19[3:23:4] */
  for (rr=w10, ss=w19+3; ss!=w19+23; ss+=4) *rr++ = *ss;
  /* #46: @10 = @10' */
  /* #47: @17 = horzcat(@1, @6, @10) */
  rr=w17;
  for (i=0, cs=w1; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w6; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<5; ++i) *rr++ = *cs++;
  /* #48: @20 = tcn(@17) */
  arg1[0]=w17;
  res1[0]=w20;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #49: @17 = (2.*@20) */
  for (i=0, rr=w17, cs=w20; i<30; ++i) *rr++ = (2.* *cs++ );
  /* #50: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<30; ++i) (*rr++) += (*cs++);
  /* #51: @14 = 0.005 */
  w14 = 5.0000000000000001e-03;
  /* #52: @17 = @20' */
  for (i=0, rr=w17, cs=w20; i<6; ++i) for (j=0; j<5; ++j) rr[i+j*6] = *cs++;
  /* #53: @1 = @17[:30:6;3:6] */
  for (rr=w1, ss=w17+0; ss!=w17+30; ss+=6) for (tt=ss+3; tt!=ss+6; tt+=1) *rr++ = *tt;
  /* #54: @0 = @1' */
  for (i=0, rr=w0, cs=w1; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #55: @10 = @17[2:32:6] */
  for (rr=w10, ss=w17+2; ss!=w17+32; ss+=6) *rr++ = *ss;
  /* #56: @10 = @10' */
  /* #57: @19 = horzcat(@0, @10) */
  rr=w19;
  for (i=0, cs=w0; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<5; ++i) *rr++ = *cs++;
  /* #58: @11 = @19' */
  for (i=0, rr=w11, cs=w19; i<4; ++i) for (j=0; j<5; ++j) rr[i+j*4] = *cs++;
  /* #59: @11 = (@14*@11) */
  for (i=0, rr=w11, cs=w11; i<20; ++i) (*rr++)  = (w14*(*cs++));
  /* #60: @11 = (@12+@11) */
  for (i=0, rr=w11, cr=w12, cs=w11; i<20; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #61: @0 = @11[:20:4;:3] */
  for (rr=w0, ss=w11+0; ss!=w11+20; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #62: @1 = @0' */
  for (i=0, rr=w1, cs=w0; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #63: @10 = @11[3:23:4] */
  for (rr=w10, ss=w11+3; ss!=w11+23; ss+=4) *rr++ = *ss;
  /* #64: @10 = @10' */
  /* #65: @17 = horzcat(@1, @6, @10) */
  rr=w17;
  for (i=0, cs=w1; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w6; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<5; ++i) *rr++ = *cs++;
  /* #66: @20 = tcn(@17) */
  arg1[0]=w17;
  res1[0]=w20;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #67: @17 = (2.*@20) */
  for (i=0, rr=w17, cs=w20; i<30; ++i) *rr++ = (2.* *cs++ );
  /* #68: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<30; ++i) (*rr++) += (*cs++);
  /* #69: @14 = 0.01 */
  w14 = 1.0000000000000000e-02;
  /* #70: @17 = @20' */
  for (i=0, rr=w17, cs=w20; i<6; ++i) for (j=0; j<5; ++j) rr[i+j*6] = *cs++;
  /* #71: @1 = @17[:30:6;3:6] */
  for (rr=w1, ss=w17+0; ss!=w17+30; ss+=6) for (tt=ss+3; tt!=ss+6; tt+=1) *rr++ = *tt;
  /* #72: @0 = @1' */
  for (i=0, rr=w0, cs=w1; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #73: @10 = @17[2:32:6] */
  for (rr=w10, ss=w17+2; ss!=w17+32; ss+=6) *rr++ = *ss;
  /* #74: @10 = @10' */
  /* #75: @11 = horzcat(@0, @10) */
  rr=w11;
  for (i=0, cs=w0; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<5; ++i) *rr++ = *cs++;
  /* #76: @19 = @11' */
  for (i=0, rr=w19, cs=w11; i<4; ++i) for (j=0; j<5; ++j) rr[i+j*4] = *cs++;
  /* #77: @19 = (@14*@19) */
  for (i=0, rr=w19, cs=w19; i<20; ++i) (*rr++)  = (w14*(*cs++));
  /* #78: @12 = (@12+@19) */
  for (i=0, rr=w12, cs=w19; i<20; ++i) (*rr++) += (*cs++);
  /* #79: @0 = @12[:20:4;:3] */
  for (rr=w0, ss=w12+0; ss!=w12+20; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #80: @1 = @0' */
  for (i=0, rr=w1, cs=w0; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #81: @10 = @12[3:23:4] */
  for (rr=w10, ss=w12+3; ss!=w12+23; ss+=4) *rr++ = *ss;
  /* #82: @10 = @10' */
  /* #83: @17 = horzcat(@1, @6, @10) */
  rr=w17;
  for (i=0, cs=w1; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w6; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<5; ++i) *rr++ = *cs++;
  /* #84: @20 = tcn(@17) */
  arg1[0]=w17;
  res1[0]=w20;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #85: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<30; ++i) (*rr++) += (*cs++);
  /* #86: @18 = (@5*@18) */
  for (i=0, rr=w18, cs=w18; i<30; ++i) (*rr++)  = (w5*(*cs++));
  /* #87: @4 = (@4+@18) */
  for (i=0, rr=w4, cs=w18; i<30; ++i) (*rr++) += (*cs++);
  /* #88: output[0][0] = @4 */
  casadi_copy(w4, 30, res[0]);
  /* #89: @13 = @6[:10:5;1:5] */
  for (rr=w13, ss=w6+0; ss!=w6+10; ss+=5) for (tt=ss+1; tt!=ss+5; tt+=1) *rr++ = *tt;
  /* #90: @21 = @13' */
  for (i=0, rr=w21, cs=w13; i<2; ++i) for (j=0; j<4; ++j) rr[i+j*2] = *cs++;
  /* #91: @16 = @6[:10:5] */
  for (rr=w16, ss=w6+0; ss!=w6+10; ss+=5) *rr++ = *ss;
  /* #92: @16 = @16' */
  /* #93: @6 = horzcat(@21, @16) */
  rr=w6;
  for (i=0, cs=w21; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<2; ++i) *rr++ = *cs++;
  /* #94: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<5; ++i) for (j=0; j<2; ++j) rr[i+j*5] = *cs++;
  /* #95: output[0][1] = @7 */
  if (res[0]) casadi_copy(w7, 10, res[0]+30);
  return 0;
}

CASADI_SYMBOL_EXPORT int wr_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wr_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wr_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wr_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wr_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wr_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wr_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void wr_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wr_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int wr_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real wr_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wr_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wr_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wr_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wr_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wr_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 366;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
