/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wr_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[31] = {27, 1, 0, 27, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26};

/* wr_expl_ode_fun:(i0[3],i1[3],i2[27])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+3, w1, *w2=w+7, w3, w4, w5, w6, *w7=w+13, *w8=w+16, *w9=w+19, *w10=w+22, *w11=w+40, *w12=w+46;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = @0[0] */
  for (rr=(&w1), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 2, w2);
  /* #3: @3 = @2[0] */
  for (rr=(&w3), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #4: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #5: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #6: @3 = (@3*@4) */
  w3 *= w4;
  /* #7: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][2] : 0;
  /* #8: @3 = (@3*@4) */
  w3 *= w4;
  /* #9: @1 = (@1+@3) */
  w1 += w3;
  /* #10: @3 = @0[1] */
  for (rr=(&w3), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #11: @5 = @2[1] */
  for (rr=(&w5), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #12: @6 = @0[2] */
  for (rr=(&w6), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #13: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #14: @5 = (@5*@6) */
  w5 *= w6;
  /* #15: @5 = (@5*@4) */
  w5 *= w4;
  /* #16: @3 = (@3+@5) */
  w3 += w5;
  /* #17: @5 = @0[2] */
  for (rr=(&w5), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #18: @6 = @2[1] */
  for (rr=(&w6), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #19: @6 = (@6*@4) */
  w6 *= w4;
  /* #20: @5 = (@5+@6) */
  w5 += w6;
  /* #21: @7 = vertcat(@1, @3, @5) */
  rr=w7;
  *rr++ = w1;
  *rr++ = w3;
  *rr++ = w5;
  /* #22: @8 = input[2][1] */
  casadi_copy(arg[2] ? arg[2]+6 : 0, 3, w8);
  /* #23: @9 = zeros(3x1) */
  casadi_clear(w9, 3);
  /* #24: @10 = input[2][2] */
  casadi_copy(arg[2] ? arg[2]+9 : 0, 18, w10);
  /* #25: @11 = vertcat(@0, @2, @4) */
  rr=w11;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<2; ++i) *rr++ = *cs++;
  *rr++ = w4;
  /* #26: @12 = input[2][0] */
  casadi_copy(arg[2], 6, w12);
  /* #27: @11 = (@11-@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) -= (*cs++);
  /* #28: @9 = mac(@10,@11,@9) */
  for (i=0, rr=w9; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w10+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*3]**tt++;
  /* #29: @8 = (@8+@9) */
  for (i=0, rr=w8, cs=w9; i<3; ++i) (*rr++) += (*cs++);
  /* #30: @7 = (@7+@8) */
  for (i=0, rr=w7, cs=w8; i<3; ++i) (*rr++) += (*cs++);
  /* #31: output[0][0] = @7 */
  casadi_copy(w7, 3, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int wr_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wr_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wr_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wr_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wr_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wr_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wr_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void wr_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wr_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int wr_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real wr_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wr_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wr_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wr_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wr_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wr_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 52;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
