/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wr_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[7] = {6, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[27] = {3, 6, 0, 3, 6, 9, 12, 15, 18, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s4[5] = {6, 1, 0, 1, 3};
static const casadi_int casadi_s5[6] = {3, 1, 0, 2, 1, 2};
static const casadi_int casadi_s6[5] = {6, 1, 0, 1, 4};
static const casadi_int casadi_s7[5] = {6, 1, 0, 1, 5};
static const casadi_int casadi_s8[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s9[31] = {27, 1, 0, 27, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26};

/* wr_expl_vde_forw:(i0[3],i1[3x3],i2[3x3],i3[3],i4[27])->(o0[3],o1[3x3],o2[3x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+3, w1, *w2=w+7, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, *w16=w+22, *w17=w+25, *w18=w+28, *w19=w+31, *w20=w+49, *w21=w+55, *w22=w+61, w23, *w24=w+71, *w27=w+74, *w28=w+77;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = @0[0] */
  for (rr=(&w1), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #2: @2 = input[3][0] */
  casadi_copy(arg[3], 2, w2);
  /* #3: @3 = @2[0] */
  for (rr=(&w3), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #4: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #5: @5 = cos(@4) */
  w5 = cos( w4 );
  /* #6: @6 = (@3*@5) */
  w6  = (w3*w5);
  /* #7: @7 = input[3][1] */
  w7 = arg[3] ? arg[3][2] : 0;
  /* #8: @8 = (@6*@7) */
  w8  = (w6*w7);
  /* #9: @1 = (@1+@8) */
  w1 += w8;
  /* #10: @8 = @0[1] */
  for (rr=(&w8), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #11: @9 = @2[1] */
  for (rr=(&w9), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #12: @10 = @0[2] */
  for (rr=(&w10), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #13: @11 = sin(@10) */
  w11 = sin( w10 );
  /* #14: @12 = (@9*@11) */
  w12  = (w9*w11);
  /* #15: @13 = (@12*@7) */
  w13  = (w12*w7);
  /* #16: @8 = (@8+@13) */
  w8 += w13;
  /* #17: @13 = @0[2] */
  for (rr=(&w13), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #18: @14 = @2[1] */
  for (rr=(&w14), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #19: @15 = (@14*@7) */
  w15  = (w14*w7);
  /* #20: @13 = (@13+@15) */
  w13 += w15;
  /* #21: @16 = vertcat(@1, @8, @13) */
  rr=w16;
  *rr++ = w1;
  *rr++ = w8;
  *rr++ = w13;
  /* #22: @17 = input[4][1] */
  casadi_copy(arg[4] ? arg[4]+6 : 0, 3, w17);
  /* #23: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #24: @19 = input[4][2] */
  casadi_copy(arg[4] ? arg[4]+9 : 0, 18, w19);
  /* #25: @20 = vertcat(@0, @2, @7) */
  rr=w20;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<2; ++i) *rr++ = *cs++;
  *rr++ = w7;
  /* #26: @21 = input[4][0] */
  casadi_copy(arg[4], 6, w21);
  /* #27: @20 = (@20-@21) */
  for (i=0, rr=w20, cs=w21; i<6; ++i) (*rr++) -= (*cs++);
  /* #28: @18 = mac(@19,@20,@18) */
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w20+i*6; k<6; ++k) *rr += ss[k*3]**tt++;
  /* #29: @17 = (@17+@18) */
  for (i=0, rr=w17, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #30: @16 = (@16+@17) */
  for (i=0, rr=w16, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #31: output[0][0] = @16 */
  casadi_copy(w16, 3, res[0]);
  /* #32: @22 = input[1][0] */
  casadi_copy(arg[1], 9, w22);
  /* #33: {@16, @17, @18} = horzsplit(@22) */
  casadi_copy(w22, 3, w16);
  casadi_copy(w22+3, 3, w17);
  casadi_copy(w22+6, 3, w18);
  /* #34: @1 = @16[0] */
  for (rr=(&w1), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #35: @8 = sin(@4) */
  w8 = sin( w4 );
  /* #36: @13 = @16[2] */
  for (rr=(&w13), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #37: @13 = (@8*@13) */
  w13  = (w8*w13);
  /* #38: @13 = (@3*@13) */
  w13  = (w3*w13);
  /* #39: @13 = (@7*@13) */
  w13  = (w7*w13);
  /* #40: @1 = (@1-@13) */
  w1 -= w13;
  /* #41: @13 = @16[1] */
  for (rr=(&w13), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #42: @15 = cos(@10) */
  w15 = cos( w10 );
  /* #43: @23 = @16[2] */
  for (rr=(&w23), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #44: @23 = (@15*@23) */
  w23  = (w15*w23);
  /* #45: @23 = (@9*@23) */
  w23  = (w9*w23);
  /* #46: @23 = (@7*@23) */
  w23  = (w7*w23);
  /* #47: @13 = (@13+@23) */
  w13 += w23;
  /* #48: @23 = @16[2] */
  for (rr=(&w23), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #49: @0 = vertcat(@1, @13, @23) */
  rr=w0;
  *rr++ = w1;
  *rr++ = w13;
  *rr++ = w23;
  /* #50: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #51: @25 = zeros(2x1,0nz) */
  /* #52: @26 = 00 */
  /* #53: @27 = vertcat(@16, @25, @26) */
  rr=w27;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  /* #54: @24 = mac(@19,@27,@24) */
  casadi_mtimes(w19, casadi_s2, w27, casadi_s1, w24, casadi_s0, w, 0);
  /* #55: @0 = (@0+@24) */
  for (i=0, rr=w0, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #56: output[1][0] = @0 */
  casadi_copy(w0, 3, res[1]);
  /* #57: @1 = @17[0] */
  for (rr=(&w1), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #58: @13 = @17[2] */
  for (rr=(&w13), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #59: @13 = (@8*@13) */
  w13  = (w8*w13);
  /* #60: @13 = (@3*@13) */
  w13  = (w3*w13);
  /* #61: @13 = (@7*@13) */
  w13  = (w7*w13);
  /* #62: @1 = (@1-@13) */
  w1 -= w13;
  /* #63: @13 = @17[1] */
  for (rr=(&w13), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #64: @23 = @17[2] */
  for (rr=(&w23), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #65: @23 = (@15*@23) */
  w23  = (w15*w23);
  /* #66: @23 = (@9*@23) */
  w23  = (w9*w23);
  /* #67: @23 = (@7*@23) */
  w23  = (w7*w23);
  /* #68: @13 = (@13+@23) */
  w13 += w23;
  /* #69: @23 = @17[2] */
  for (rr=(&w23), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #70: @0 = vertcat(@1, @13, @23) */
  rr=w0;
  *rr++ = w1;
  *rr++ = w13;
  *rr++ = w23;
  /* #71: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #72: @25 = zeros(2x1,0nz) */
  /* #73: @26 = 00 */
  /* #74: @27 = vertcat(@17, @25, @26) */
  rr=w27;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  /* #75: @24 = mac(@19,@27,@24) */
  casadi_mtimes(w19, casadi_s2, w27, casadi_s1, w24, casadi_s0, w, 0);
  /* #76: @0 = (@0+@24) */
  for (i=0, rr=w0, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #77: output[1][1] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+3);
  /* #78: @1 = @18[0] */
  for (rr=(&w1), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #79: @13 = @18[2] */
  for (rr=(&w13), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #80: @8 = (@8*@13) */
  w8 *= w13;
  /* #81: @8 = (@3*@8) */
  w8  = (w3*w8);
  /* #82: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #83: @1 = (@1-@8) */
  w1 -= w8;
  /* #84: @8 = @18[1] */
  for (rr=(&w8), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #85: @13 = @18[2] */
  for (rr=(&w13), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #86: @15 = (@15*@13) */
  w15 *= w13;
  /* #87: @15 = (@9*@15) */
  w15  = (w9*w15);
  /* #88: @15 = (@7*@15) */
  w15  = (w7*w15);
  /* #89: @8 = (@8+@15) */
  w8 += w15;
  /* #90: @15 = @18[2] */
  for (rr=(&w15), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #91: @0 = vertcat(@1, @8, @15) */
  rr=w0;
  *rr++ = w1;
  *rr++ = w8;
  *rr++ = w15;
  /* #92: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #93: @25 = zeros(2x1,0nz) */
  /* #94: @26 = 00 */
  /* #95: @27 = vertcat(@18, @25, @26) */
  rr=w27;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  /* #96: @24 = mac(@19,@27,@24) */
  casadi_mtimes(w19, casadi_s2, w27, casadi_s1, w24, casadi_s0, w, 0);
  /* #97: @0 = (@0+@24) */
  for (i=0, rr=w0, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #98: output[1][2] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+6);
  /* #99: @22 = zeros(3x3) */
  casadi_clear(w22, 9);
  /* #100: @1 = ones(3x1,1nz) */
  w1 = 1.;
  /* #101: {@8, NULL} = vertsplit(@1) */
  w8 = w1;
  /* #102: @1 = @8[0] */
  for (rr=(&w1), ss=(&w8)+0; ss!=(&w8)+1; ss+=1) *rr++ = *ss;
  /* #103: @5 = (@5*@1) */
  w5 *= w1;
  /* #104: @5 = (@7*@5) */
  w5  = (w7*w5);
  /* #105: @25 = 00 */
  /* #106: @26 = 00 */
  /* #107: @1 = vertcat(@5, @25, @26) */
  rr=(&w1);
  *rr++ = w5;
  /* #108: @0 = dense(@1) */
  casadi_densify((&w1), casadi_s3, w0, 0);
  /* #109: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #110: @25 = zeros(3x1,0nz) */
  /* #111: @26 = 00 */
  /* #112: @1 = vertcat(@25, @8, @26) */
  rr=(&w1);
  *rr++ = w8;
  /* #113: @24 = mac(@19,@1,@24) */
  casadi_mtimes(w19, casadi_s2, (&w1), casadi_s4, w24, casadi_s0, w, 0);
  /* #114: @0 = (@0+@24) */
  for (i=0, rr=w0, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #115: (@22[:9:3] = @0) */
  for (rr=w22+0, ss=w0; rr!=w22+9; rr+=3) *rr = *ss++;
  /* #116: @25 = 00 */
  /* #117: @1 = ones(3x1,1nz) */
  w1 = 1.;
  /* #118: {@8, NULL} = vertsplit(@1) */
  w8 = w1;
  /* #119: @1 = @8[0] */
  for (rr=(&w1), ss=(&w8)+0; ss!=(&w8)+1; ss+=1) *rr++ = *ss;
  /* #120: @11 = (@11*@1) */
  w11 *= w1;
  /* #121: @11 = (@7*@11) */
  w11  = (w7*w11);
  /* #122: @1 = @8[0] */
  for (rr=(&w1), ss=(&w8)+0; ss!=(&w8)+1; ss+=1) *rr++ = *ss;
  /* #123: @1 = (@7*@1) */
  w1  = (w7*w1);
  /* #124: @2 = vertcat(@25, @11, @1) */
  rr=w2;
  *rr++ = w11;
  *rr++ = w1;
  /* #125: @0 = dense(@2) */
  casadi_densify(w2, casadi_s5, w0, 0);
  /* #126: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #127: @25 = zeros(3x1,0nz) */
  /* #128: @26 = 00 */
  /* #129: @11 = vertcat(@25, @8, @26) */
  rr=(&w11);
  *rr++ = w8;
  /* #130: @24 = mac(@19,@11,@24) */
  casadi_mtimes(w19, casadi_s2, (&w11), casadi_s6, w24, casadi_s0, w, 0);
  /* #131: @0 = (@0+@24) */
  for (i=0, rr=w0, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #132: (@22[1:10:3] = @0) */
  for (rr=w22+1, ss=w0; rr!=w22+10; rr+=3) *rr = *ss++;
  /* #133: @11 = ones(3x1,1nz) */
  w11 = 1.;
  /* #134: {NULL, @8} = vertsplit(@11) */
  w8 = w11;
  /* #135: @6 = (@6*@8) */
  w6 *= w8;
  /* #136: @12 = (@12*@8) */
  w12 *= w8;
  /* #137: @14 = (@14*@8) */
  w14 *= w8;
  /* #138: @0 = vertcat(@6, @12, @14) */
  rr=w0;
  *rr++ = w6;
  *rr++ = w12;
  *rr++ = w14;
  /* #139: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #140: @25 = zeros(3x1,0nz) */
  /* #141: @26 = zeros(2x1,0nz) */
  /* #142: @6 = vertcat(@25, @26, @8) */
  rr=(&w6);
  *rr++ = w8;
  /* #143: @24 = mac(@19,@6,@24) */
  casadi_mtimes(w19, casadi_s2, (&w6), casadi_s7, w24, casadi_s0, w, 0);
  /* #144: @0 = (@0+@24) */
  for (i=0, rr=w0, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #145: (@22[2:11:3] = @0) */
  for (rr=w22+2, ss=w0; rr!=w22+11; rr+=3) *rr = *ss++;
  /* #146: @28 = @22' */
  for (i=0, rr=w28, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #147: @22 = input[2][0] */
  casadi_copy(arg[2], 9, w22);
  /* #148: {@0, @24, @27} = horzsplit(@22) */
  casadi_copy(w22, 3, w0);
  casadi_copy(w22+3, 3, w24);
  casadi_copy(w22+6, 3, w27);
  /* #149: @6 = @0[0] */
  for (rr=(&w6), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #150: @4 = sin(@4) */
  w4 = sin( w4 );
  /* #151: @8 = @0[2] */
  for (rr=(&w8), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #152: @8 = (@4*@8) */
  w8  = (w4*w8);
  /* #153: @8 = (@3*@8) */
  w8  = (w3*w8);
  /* #154: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #155: @6 = (@6-@8) */
  w6 -= w8;
  /* #156: @8 = @0[1] */
  for (rr=(&w8), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #157: @10 = cos(@10) */
  w10 = cos( w10 );
  /* #158: @12 = @0[2] */
  for (rr=(&w12), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #159: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #160: @12 = (@9*@12) */
  w12  = (w9*w12);
  /* #161: @12 = (@7*@12) */
  w12  = (w7*w12);
  /* #162: @8 = (@8+@12) */
  w8 += w12;
  /* #163: @12 = @0[2] */
  for (rr=(&w12), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #164: @18 = vertcat(@6, @8, @12) */
  rr=w18;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w12;
  /* #165: @17 = zeros(3x1) */
  casadi_clear(w17, 3);
  /* #166: @25 = zeros(2x1,0nz) */
  /* #167: @26 = 00 */
  /* #168: @16 = vertcat(@0, @25, @26) */
  rr=w16;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  /* #169: @17 = mac(@19,@16,@17) */
  casadi_mtimes(w19, casadi_s2, w16, casadi_s1, w17, casadi_s0, w, 0);
  /* #170: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #171: @6 = @24[0] */
  for (rr=(&w6), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #172: @8 = @24[2] */
  for (rr=(&w8), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #173: @8 = (@4*@8) */
  w8  = (w4*w8);
  /* #174: @8 = (@3*@8) */
  w8  = (w3*w8);
  /* #175: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #176: @6 = (@6-@8) */
  w6 -= w8;
  /* #177: @8 = @24[1] */
  for (rr=(&w8), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #178: @12 = @24[2] */
  for (rr=(&w12), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #179: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #180: @12 = (@9*@12) */
  w12  = (w9*w12);
  /* #181: @12 = (@7*@12) */
  w12  = (w7*w12);
  /* #182: @8 = (@8+@12) */
  w8 += w12;
  /* #183: @12 = @24[2] */
  for (rr=(&w12), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #184: @17 = vertcat(@6, @8, @12) */
  rr=w17;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w12;
  /* #185: @16 = zeros(3x1) */
  casadi_clear(w16, 3);
  /* #186: @25 = zeros(2x1,0nz) */
  /* #187: @26 = 00 */
  /* #188: @0 = vertcat(@24, @25, @26) */
  rr=w0;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #189: @16 = mac(@19,@0,@16) */
  casadi_mtimes(w19, casadi_s2, w0, casadi_s1, w16, casadi_s0, w, 0);
  /* #190: @17 = (@17+@16) */
  for (i=0, rr=w17, cs=w16; i<3; ++i) (*rr++) += (*cs++);
  /* #191: @6 = @27[0] */
  for (rr=(&w6), ss=w27+0; ss!=w27+1; ss+=1) *rr++ = *ss;
  /* #192: @8 = @27[2] */
  for (rr=(&w8), ss=w27+2; ss!=w27+3; ss+=1) *rr++ = *ss;
  /* #193: @4 = (@4*@8) */
  w4 *= w8;
  /* #194: @3 = (@3*@4) */
  w3 *= w4;
  /* #195: @3 = (@7*@3) */
  w3  = (w7*w3);
  /* #196: @6 = (@6-@3) */
  w6 -= w3;
  /* #197: @3 = @27[1] */
  for (rr=(&w3), ss=w27+1; ss!=w27+2; ss+=1) *rr++ = *ss;
  /* #198: @4 = @27[2] */
  for (rr=(&w4), ss=w27+2; ss!=w27+3; ss+=1) *rr++ = *ss;
  /* #199: @10 = (@10*@4) */
  w10 *= w4;
  /* #200: @9 = (@9*@10) */
  w9 *= w10;
  /* #201: @7 = (@7*@9) */
  w7 *= w9;
  /* #202: @3 = (@3+@7) */
  w3 += w7;
  /* #203: @7 = @27[2] */
  for (rr=(&w7), ss=w27+2; ss!=w27+3; ss+=1) *rr++ = *ss;
  /* #204: @16 = vertcat(@6, @3, @7) */
  rr=w16;
  *rr++ = w6;
  *rr++ = w3;
  *rr++ = w7;
  /* #205: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #206: @25 = zeros(2x1,0nz) */
  /* #207: @26 = 00 */
  /* #208: @24 = vertcat(@27, @25, @26) */
  rr=w24;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  /* #209: @0 = mac(@19,@24,@0) */
  casadi_mtimes(w19, casadi_s2, w24, casadi_s1, w0, casadi_s0, w, 0);
  /* #210: @16 = (@16+@0) */
  for (i=0, rr=w16, cs=w0; i<3; ++i) (*rr++) += (*cs++);
  /* #211: @22 = horzcat(@18, @17, @16) */
  rr=w22;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  /* #212: @28 = (@28+@22) */
  for (i=0, rr=w28, cs=w22; i<9; ++i) (*rr++) += (*cs++);
  /* #213: output[2][0] = @28 */
  casadi_copy(w28, 9, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wr_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wr_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wr_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void wr_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wr_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int wr_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real wr_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wr_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wr_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wr_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s8;
    case 2: return casadi_s8;
    case 3: return casadi_s0;
    case 4: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wr_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s8;
    case 2: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 86;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
