/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wr_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[44] = {40, 1, 0, 40, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};

static const casadi_real casadi_c0[3] = {2.5594159083527235e-01, -1.4891314409307613e-01, -7.4133401798264456e-02};

/* wr_dyn_disc_phi_fun:(i0[40],i1[2],i2[])->(o0[40]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, *w1=w+15, *w2=w+30, *w3=w+45, *w4=w+60, w5, *w6=w+91, *w7=w+101, *w8=w+111, *w9=w+151, *w10=w+191, *w11=w+196, *w12=w+216, *w13=w+236, *w14=w+248, *w15=w+251, *w16=w+254, w17, *w18=w+285, *w19=w+315, *w20=w+335, *w21=w+365, *w22=w+373, *w23=w+375;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 15, w0);
  /* #1: @0 = reshape(@0) */
  /* #2: @1 = @0' */
  for (i=0, rr=w1, cs=w0; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #3: @2 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+15 : 0, 15, w2);
  /* #4: @2 = reshape(@2) */
  /* #5: @3 = @2' */
  for (i=0, rr=w3, cs=w2; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #6: @4 = horzcat(@1, @3) */
  rr=w4;
  for (i=0, cs=w1; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<15; ++i) *rr++ = *cs++;
  /* #7: @5 = 0.0166667 */
  w5 = 1.6666666666666666e-02;
  /* #8: @1 = zeros(5x3) */
  casadi_clear(w1, 15);
  /* #9: @3 = @0' */
  for (i=0, rr=w3, cs=w0; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #10: @0 = @2' */
  for (i=0, rr=w0, cs=w2; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #11: @6 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+30 : 0, 10, w6);
  /* #12: @6 = reshape(@6) */
  /* #13: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<5; ++i) for (j=0; j<2; ++j) rr[i+j*5] = *cs++;
  /* #14: @8 = horzcat(@3, @0, @7) */
  rr=w8;
  for (i=0, cs=w3; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w0; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<10; ++i) *rr++ = *cs++;
  /* #15: @9 = @8' */
  for (i=0, rr=w9, cs=w8; i<8; ++i) for (j=0; j<5; ++j) rr[i+j*8] = *cs++;
  /* #16: @3 = @9[:40:8;3:6] */
  for (rr=w3, ss=w9+0; ss!=w9+40; ss+=8) for (tt=ss+3; tt!=ss+6; tt+=1) *rr++ = *tt;
  /* #17: @0 = @3' */
  for (i=0, rr=w0, cs=w3; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #18: @10 = @9[2:42:8] */
  for (rr=w10, ss=w9+2; ss!=w9+42; ss+=8) *rr++ = *ss;
  /* #19: @10 = @10' */
  /* #20: @11 = horzcat(@0, @10) */
  rr=w11;
  for (i=0, cs=w0; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<5; ++i) *rr++ = *cs++;
  /* #21: @12 = @11' */
  for (i=0, rr=w12, cs=w11; i<4; ++i) for (j=0; j<5; ++j) rr[i+j*4] = *cs++;
  /* #22: @0 = @12[:20:4;:3] */
  for (rr=w0, ss=w12+0; ss!=w12+20; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #23: @3 = @0' */
  for (i=0, rr=w3, cs=w0; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #24: @13 = @3[:15:5;1:5] */
  for (rr=w13, ss=w3+0; ss!=w3+15; ss+=5) for (tt=ss+1; tt!=ss+5; tt+=1) *rr++ = *tt;
  /* #25: (@1[:15:5;:4] = @13) */
  for (rr=w1+0, ss=w13; rr!=w1+15; rr+=5) for (tt=rr+0; tt!=rr+4; tt+=1) *tt = *ss++;
  /* #26: @14 = [[0.255942, -0.148913, -0.0741334]] */
  casadi_copy(casadi_c0, 3, w14);
  /* #27: (@1[4:19:5] = @14) */
  for (rr=w1+4, ss=w14; rr!=w1+19; rr+=5) *rr = *ss++;
  /* #28: @0 = zeros(5x3) */
  casadi_clear(w0, 15);
  /* #29: @14 = @3[1:16:5] */
  for (rr=w14, ss=w3+1; ss!=w3+16; ss+=5) *rr++ = *ss;
  /* #30: @15 = @3[:15:5] */
  for (rr=w15, ss=w3+0; ss!=w3+15; ss+=5) *rr++ = *ss;
  /* #31: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #32: (@0[:15:5] = @14) */
  for (rr=w0+0, ss=w14; rr!=w0+15; rr+=5) *rr = *ss++;
  /* #33: @14 = @3[2:17:5] */
  for (rr=w14, ss=w3+2; ss!=w3+17; ss+=5) *rr++ = *ss;
  /* #34: @15 = @3[1:16:5] */
  for (rr=w15, ss=w3+1; ss!=w3+16; ss+=5) *rr++ = *ss;
  /* #35: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #36: (@0[1:16:5] = @14) */
  for (rr=w0+1, ss=w14; rr!=w0+16; rr+=5) *rr = *ss++;
  /* #37: @14 = @3[3:18:5] */
  for (rr=w14, ss=w3+3; ss!=w3+18; ss+=5) *rr++ = *ss;
  /* #38: @15 = @3[2:17:5] */
  for (rr=w15, ss=w3+2; ss!=w3+17; ss+=5) *rr++ = *ss;
  /* #39: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #40: (@0[2:17:5] = @14) */
  for (rr=w0+2, ss=w14; rr!=w0+17; rr+=5) *rr = *ss++;
  /* #41: @14 = @3[4:19:5] */
  for (rr=w14, ss=w3+4; ss!=w3+19; ss+=5) *rr++ = *ss;
  /* #42: @15 = @3[3:18:5] */
  for (rr=w15, ss=w3+3; ss!=w3+18; ss+=5) *rr++ = *ss;
  /* #43: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #44: (@0[3:18:5] = @14) */
  for (rr=w0+3, ss=w14; rr!=w0+18; rr+=5) *rr = *ss++;
  /* #45: @14 = [[0.255942, -0.148913, -0.0741334]] */
  casadi_copy(casadi_c0, 3, w14);
  /* #46: @15 = @3[4:19:5] */
  for (rr=w15, ss=w3+4; ss!=w3+19; ss+=5) *rr++ = *ss;
  /* #47: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #48: (@0[4:19:5] = @14) */
  for (rr=w0+4, ss=w14; rr!=w0+19; rr+=5) *rr = *ss++;
  /* #49: @16 = horzcat(@1, @0) */
  rr=w16;
  for (i=0, cs=w1; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w0; i<15; ++i) *rr++ = *cs++;
  /* #50: @1 = zeros(5x3) */
  casadi_clear(w1, 15);
  /* #51: @17 = 0.05 */
  w17 = 5.0000000000000003e-02;
  /* #52: @18 = @16' */
  for (i=0, rr=w18, cs=w16; i<6; ++i) for (j=0; j<5; ++j) rr[i+j*6] = *cs++;
  /* #53: @0 = @18[:30:6;3:6] */
  for (rr=w0, ss=w18+0; ss!=w18+30; ss+=6) for (tt=ss+3; tt!=ss+6; tt+=1) *rr++ = *tt;
  /* #54: @3 = @0' */
  for (i=0, rr=w3, cs=w0; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #55: @10 = @18[2:32:6] */
  for (rr=w10, ss=w18+2; ss!=w18+32; ss+=6) *rr++ = *ss;
  /* #56: @10 = @10' */
  /* #57: @11 = horzcat(@3, @10) */
  rr=w11;
  for (i=0, cs=w3; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<5; ++i) *rr++ = *cs++;
  /* #58: @19 = @11' */
  for (i=0, rr=w19, cs=w11; i<4; ++i) for (j=0; j<5; ++j) rr[i+j*4] = *cs++;
  /* #59: @19 = (@17*@19) */
  for (i=0, rr=w19, cs=w19; i<20; ++i) (*rr++)  = (w17*(*cs++));
  /* #60: @19 = (@12+@19) */
  for (i=0, rr=w19, cr=w12, cs=w19; i<20; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #61: @3 = @19[:20:4;:3] */
  for (rr=w3, ss=w19+0; ss!=w19+20; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #62: @0 = @3' */
  for (i=0, rr=w0, cs=w3; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #63: @13 = @0[:15:5;1:5] */
  for (rr=w13, ss=w0+0; ss!=w0+15; ss+=5) for (tt=ss+1; tt!=ss+5; tt+=1) *rr++ = *tt;
  /* #64: (@1[:15:5;:4] = @13) */
  for (rr=w1+0, ss=w13; rr!=w1+15; rr+=5) for (tt=rr+0; tt!=rr+4; tt+=1) *tt = *ss++;
  /* #65: @14 = [[0.255942, -0.148913, -0.0741334]] */
  casadi_copy(casadi_c0, 3, w14);
  /* #66: (@1[4:19:5] = @14) */
  for (rr=w1+4, ss=w14; rr!=w1+19; rr+=5) *rr = *ss++;
  /* #67: @3 = zeros(5x3) */
  casadi_clear(w3, 15);
  /* #68: @14 = @0[1:16:5] */
  for (rr=w14, ss=w0+1; ss!=w0+16; ss+=5) *rr++ = *ss;
  /* #69: @15 = @0[:15:5] */
  for (rr=w15, ss=w0+0; ss!=w0+15; ss+=5) *rr++ = *ss;
  /* #70: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #71: (@3[:15:5] = @14) */
  for (rr=w3+0, ss=w14; rr!=w3+15; rr+=5) *rr = *ss++;
  /* #72: @14 = @0[2:17:5] */
  for (rr=w14, ss=w0+2; ss!=w0+17; ss+=5) *rr++ = *ss;
  /* #73: @15 = @0[1:16:5] */
  for (rr=w15, ss=w0+1; ss!=w0+16; ss+=5) *rr++ = *ss;
  /* #74: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #75: (@3[1:16:5] = @14) */
  for (rr=w3+1, ss=w14; rr!=w3+16; rr+=5) *rr = *ss++;
  /* #76: @14 = @0[3:18:5] */
  for (rr=w14, ss=w0+3; ss!=w0+18; ss+=5) *rr++ = *ss;
  /* #77: @15 = @0[2:17:5] */
  for (rr=w15, ss=w0+2; ss!=w0+17; ss+=5) *rr++ = *ss;
  /* #78: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #79: (@3[2:17:5] = @14) */
  for (rr=w3+2, ss=w14; rr!=w3+17; rr+=5) *rr = *ss++;
  /* #80: @14 = @0[4:19:5] */
  for (rr=w14, ss=w0+4; ss!=w0+19; ss+=5) *rr++ = *ss;
  /* #81: @15 = @0[3:18:5] */
  for (rr=w15, ss=w0+3; ss!=w0+18; ss+=5) *rr++ = *ss;
  /* #82: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #83: (@3[3:18:5] = @14) */
  for (rr=w3+3, ss=w14; rr!=w3+18; rr+=5) *rr = *ss++;
  /* #84: @14 = [[0.255942, -0.148913, -0.0741334]] */
  casadi_copy(casadi_c0, 3, w14);
  /* #85: @15 = @0[4:19:5] */
  for (rr=w15, ss=w0+4; ss!=w0+19; ss+=5) *rr++ = *ss;
  /* #86: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #87: (@3[4:19:5] = @14) */
  for (rr=w3+4, ss=w14; rr!=w3+19; rr+=5) *rr = *ss++;
  /* #88: @18 = horzcat(@1, @3) */
  rr=w18;
  for (i=0, cs=w1; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<15; ++i) *rr++ = *cs++;
  /* #89: @20 = (2.*@18) */
  for (i=0, rr=w20, cs=w18; i<30; ++i) *rr++ = (2.* *cs++ );
  /* #90: @16 = (@16+@20) */
  for (i=0, rr=w16, cs=w20; i<30; ++i) (*rr++) += (*cs++);
  /* #91: @1 = zeros(5x3) */
  casadi_clear(w1, 15);
  /* #92: @17 = 0.05 */
  w17 = 5.0000000000000003e-02;
  /* #93: @20 = @18' */
  for (i=0, rr=w20, cs=w18; i<6; ++i) for (j=0; j<5; ++j) rr[i+j*6] = *cs++;
  /* #94: @3 = @20[:30:6;3:6] */
  for (rr=w3, ss=w20+0; ss!=w20+30; ss+=6) for (tt=ss+3; tt!=ss+6; tt+=1) *rr++ = *tt;
  /* #95: @0 = @3' */
  for (i=0, rr=w0, cs=w3; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #96: @10 = @20[2:32:6] */
  for (rr=w10, ss=w20+2; ss!=w20+32; ss+=6) *rr++ = *ss;
  /* #97: @10 = @10' */
  /* #98: @19 = horzcat(@0, @10) */
  rr=w19;
  for (i=0, cs=w0; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<5; ++i) *rr++ = *cs++;
  /* #99: @11 = @19' */
  for (i=0, rr=w11, cs=w19; i<4; ++i) for (j=0; j<5; ++j) rr[i+j*4] = *cs++;
  /* #100: @11 = (@17*@11) */
  for (i=0, rr=w11, cs=w11; i<20; ++i) (*rr++)  = (w17*(*cs++));
  /* #101: @11 = (@12+@11) */
  for (i=0, rr=w11, cr=w12, cs=w11; i<20; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #102: @0 = @11[:20:4;:3] */
  for (rr=w0, ss=w11+0; ss!=w11+20; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #103: @3 = @0' */
  for (i=0, rr=w3, cs=w0; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #104: @13 = @3[:15:5;1:5] */
  for (rr=w13, ss=w3+0; ss!=w3+15; ss+=5) for (tt=ss+1; tt!=ss+5; tt+=1) *rr++ = *tt;
  /* #105: (@1[:15:5;:4] = @13) */
  for (rr=w1+0, ss=w13; rr!=w1+15; rr+=5) for (tt=rr+0; tt!=rr+4; tt+=1) *tt = *ss++;
  /* #106: @14 = [[0.255942, -0.148913, -0.0741334]] */
  casadi_copy(casadi_c0, 3, w14);
  /* #107: (@1[4:19:5] = @14) */
  for (rr=w1+4, ss=w14; rr!=w1+19; rr+=5) *rr = *ss++;
  /* #108: @0 = zeros(5x3) */
  casadi_clear(w0, 15);
  /* #109: @14 = @3[1:16:5] */
  for (rr=w14, ss=w3+1; ss!=w3+16; ss+=5) *rr++ = *ss;
  /* #110: @15 = @3[:15:5] */
  for (rr=w15, ss=w3+0; ss!=w3+15; ss+=5) *rr++ = *ss;
  /* #111: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #112: (@0[:15:5] = @14) */
  for (rr=w0+0, ss=w14; rr!=w0+15; rr+=5) *rr = *ss++;
  /* #113: @14 = @3[2:17:5] */
  for (rr=w14, ss=w3+2; ss!=w3+17; ss+=5) *rr++ = *ss;
  /* #114: @15 = @3[1:16:5] */
  for (rr=w15, ss=w3+1; ss!=w3+16; ss+=5) *rr++ = *ss;
  /* #115: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #116: (@0[1:16:5] = @14) */
  for (rr=w0+1, ss=w14; rr!=w0+16; rr+=5) *rr = *ss++;
  /* #117: @14 = @3[3:18:5] */
  for (rr=w14, ss=w3+3; ss!=w3+18; ss+=5) *rr++ = *ss;
  /* #118: @15 = @3[2:17:5] */
  for (rr=w15, ss=w3+2; ss!=w3+17; ss+=5) *rr++ = *ss;
  /* #119: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #120: (@0[2:17:5] = @14) */
  for (rr=w0+2, ss=w14; rr!=w0+17; rr+=5) *rr = *ss++;
  /* #121: @14 = @3[4:19:5] */
  for (rr=w14, ss=w3+4; ss!=w3+19; ss+=5) *rr++ = *ss;
  /* #122: @15 = @3[3:18:5] */
  for (rr=w15, ss=w3+3; ss!=w3+18; ss+=5) *rr++ = *ss;
  /* #123: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #124: (@0[3:18:5] = @14) */
  for (rr=w0+3, ss=w14; rr!=w0+18; rr+=5) *rr = *ss++;
  /* #125: @14 = [[0.255942, -0.148913, -0.0741334]] */
  casadi_copy(casadi_c0, 3, w14);
  /* #126: @15 = @3[4:19:5] */
  for (rr=w15, ss=w3+4; ss!=w3+19; ss+=5) *rr++ = *ss;
  /* #127: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #128: (@0[4:19:5] = @14) */
  for (rr=w0+4, ss=w14; rr!=w0+19; rr+=5) *rr = *ss++;
  /* #129: @20 = horzcat(@1, @0) */
  rr=w20;
  for (i=0, cs=w1; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w0; i<15; ++i) *rr++ = *cs++;
  /* #130: @18 = (2.*@20) */
  for (i=0, rr=w18, cs=w20; i<30; ++i) *rr++ = (2.* *cs++ );
  /* #131: @16 = (@16+@18) */
  for (i=0, rr=w16, cs=w18; i<30; ++i) (*rr++) += (*cs++);
  /* #132: @1 = zeros(5x3) */
  casadi_clear(w1, 15);
  /* #133: @17 = 0.1 */
  w17 = 1.0000000000000001e-01;
  /* #134: @18 = @20' */
  for (i=0, rr=w18, cs=w20; i<6; ++i) for (j=0; j<5; ++j) rr[i+j*6] = *cs++;
  /* #135: @0 = @18[:30:6;3:6] */
  for (rr=w0, ss=w18+0; ss!=w18+30; ss+=6) for (tt=ss+3; tt!=ss+6; tt+=1) *rr++ = *tt;
  /* #136: @3 = @0' */
  for (i=0, rr=w3, cs=w0; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #137: @10 = @18[2:32:6] */
  for (rr=w10, ss=w18+2; ss!=w18+32; ss+=6) *rr++ = *ss;
  /* #138: @10 = @10' */
  /* #139: @11 = horzcat(@3, @10) */
  rr=w11;
  for (i=0, cs=w3; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<5; ++i) *rr++ = *cs++;
  /* #140: @19 = @11' */
  for (i=0, rr=w19, cs=w11; i<4; ++i) for (j=0; j<5; ++j) rr[i+j*4] = *cs++;
  /* #141: @19 = (@17*@19) */
  for (i=0, rr=w19, cs=w19; i<20; ++i) (*rr++)  = (w17*(*cs++));
  /* #142: @12 = (@12+@19) */
  for (i=0, rr=w12, cs=w19; i<20; ++i) (*rr++) += (*cs++);
  /* #143: @3 = @12[:20:4;:3] */
  for (rr=w3, ss=w12+0; ss!=w12+20; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #144: @0 = @3' */
  for (i=0, rr=w0, cs=w3; i<5; ++i) for (j=0; j<3; ++j) rr[i+j*5] = *cs++;
  /* #145: @13 = @0[:15:5;1:5] */
  for (rr=w13, ss=w0+0; ss!=w0+15; ss+=5) for (tt=ss+1; tt!=ss+5; tt+=1) *rr++ = *tt;
  /* #146: (@1[:15:5;:4] = @13) */
  for (rr=w1+0, ss=w13; rr!=w1+15; rr+=5) for (tt=rr+0; tt!=rr+4; tt+=1) *tt = *ss++;
  /* #147: @14 = [[0.255942, -0.148913, -0.0741334]] */
  casadi_copy(casadi_c0, 3, w14);
  /* #148: (@1[4:19:5] = @14) */
  for (rr=w1+4, ss=w14; rr!=w1+19; rr+=5) *rr = *ss++;
  /* #149: @3 = zeros(5x3) */
  casadi_clear(w3, 15);
  /* #150: @14 = @0[1:16:5] */
  for (rr=w14, ss=w0+1; ss!=w0+16; ss+=5) *rr++ = *ss;
  /* #151: @15 = @0[:15:5] */
  for (rr=w15, ss=w0+0; ss!=w0+15; ss+=5) *rr++ = *ss;
  /* #152: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #153: (@3[:15:5] = @14) */
  for (rr=w3+0, ss=w14; rr!=w3+15; rr+=5) *rr = *ss++;
  /* #154: @14 = @0[2:17:5] */
  for (rr=w14, ss=w0+2; ss!=w0+17; ss+=5) *rr++ = *ss;
  /* #155: @15 = @0[1:16:5] */
  for (rr=w15, ss=w0+1; ss!=w0+16; ss+=5) *rr++ = *ss;
  /* #156: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #157: (@3[1:16:5] = @14) */
  for (rr=w3+1, ss=w14; rr!=w3+16; rr+=5) *rr = *ss++;
  /* #158: @14 = @0[3:18:5] */
  for (rr=w14, ss=w0+3; ss!=w0+18; ss+=5) *rr++ = *ss;
  /* #159: @15 = @0[2:17:5] */
  for (rr=w15, ss=w0+2; ss!=w0+17; ss+=5) *rr++ = *ss;
  /* #160: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #161: (@3[2:17:5] = @14) */
  for (rr=w3+2, ss=w14; rr!=w3+17; rr+=5) *rr = *ss++;
  /* #162: @14 = @0[4:19:5] */
  for (rr=w14, ss=w0+4; ss!=w0+19; ss+=5) *rr++ = *ss;
  /* #163: @15 = @0[3:18:5] */
  for (rr=w15, ss=w0+3; ss!=w0+18; ss+=5) *rr++ = *ss;
  /* #164: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #165: (@3[3:18:5] = @14) */
  for (rr=w3+3, ss=w14; rr!=w3+18; rr+=5) *rr = *ss++;
  /* #166: @14 = [[0.255942, -0.148913, -0.0741334]] */
  casadi_copy(casadi_c0, 3, w14);
  /* #167: @15 = @0[4:19:5] */
  for (rr=w15, ss=w0+4; ss!=w0+19; ss+=5) *rr++ = *ss;
  /* #168: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #169: (@3[4:19:5] = @14) */
  for (rr=w3+4, ss=w14; rr!=w3+19; rr+=5) *rr = *ss++;
  /* #170: @18 = horzcat(@1, @3) */
  rr=w18;
  for (i=0, cs=w1; i<15; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<15; ++i) *rr++ = *cs++;
  /* #171: @16 = (@16+@18) */
  for (i=0, rr=w16, cs=w18; i<30; ++i) (*rr++) += (*cs++);
  /* #172: @16 = (@5*@16) */
  for (i=0, rr=w16, cs=w16; i<30; ++i) (*rr++)  = (w5*(*cs++));
  /* #173: @4 = (@4+@16) */
  for (i=0, rr=w4, cs=w16; i<30; ++i) (*rr++) += (*cs++);
  /* #174: output[0][0] = @4 */
  casadi_copy(w4, 30, res[0]);
  /* #175: @21 = @9[:32:8;6:8] */
  for (rr=w21, ss=w9+0; ss!=w9+32; ss+=8) for (tt=ss+6; tt!=ss+8; tt+=1) *rr++ = *tt;
  /* #176: @5 = input[1][0] */
  w5 = arg[1] ? arg[1][0] : 0;
  /* #177: @17 = input[1][1] */
  w17 = arg[1] ? arg[1][1] : 0;
  /* #178: @22 = vertcat(@5, @17) */
  rr=w22;
  *rr++ = w5;
  *rr++ = w17;
  /* #179: @7 = horzcat(@21, @22) */
  rr=w7;
  for (i=0, cs=w21; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<2; ++i) *rr++ = *cs++;
  /* #180: @6 = @7' */
  for (i=0, rr=w6, cs=w7; i<5; ++i) for (j=0; j<2; ++j) rr[i+j*5] = *cs++;
  /* #181: @21 = @6[:10:5;1:5] */
  for (rr=w21, ss=w6+0; ss!=w6+10; ss+=5) for (tt=ss+1; tt!=ss+5; tt+=1) *rr++ = *tt;
  /* #182: @23 = @21' */
  for (i=0, rr=w23, cs=w21; i<2; ++i) for (j=0; j<4; ++j) rr[i+j*2] = *cs++;
  /* #183: @22 = @6[:10:5] */
  for (rr=w22, ss=w6+0; ss!=w6+10; ss+=5) *rr++ = *ss;
  /* #184: @22 = @22' */
  /* #185: @6 = horzcat(@23, @22) */
  rr=w6;
  for (i=0, cs=w23; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<2; ++i) *rr++ = *cs++;
  /* #186: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<5; ++i) for (j=0; j<2; ++j) rr[i+j*5] = *cs++;
  /* #187: output[0][1] = @7 */
  if (res[0]) casadi_copy(w7, 10, res[0]+30);
  return 0;
}

CASADI_SYMBOL_EXPORT int wr_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wr_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wr_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wr_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wr_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wr_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wr_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void wr_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wr_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int wr_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real wr_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wr_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wr_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wr_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wr_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wr_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 383;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
